### ISSUE TITLE
Indentation broken for some functions on MATLAB R2021b

### ISSUE THREAD

**Issue by danielmeer** [davidvarga/MBeautifier#111]
I don't know why but on MATLAB R2021b the call to `editorPage.smartIndentContents();` does not always indent the code correctly.

Not all functions are affected:
- Working: `MBeautify.formatFile()`, `MBeautify.formatFileNoEditor()`, `MBeautify.formatFiles()`
- Not working: `MBeautify.formatCurrentEditorPage()`, `MBeautify.formatEditorSelection()`

Example:
```matlab
function testfunc()
    a = 1;
    b = 2;
    if a == 1
        b = 3;
    else
        b = 4;
    end
    b = 6;
end
```

gets formatted to
```matlab
function testfunc()
    a = 1;
    b = 2;
    if a == 1
        b = 3;
        else
            b = 4;
        end
        b = 6;
end
```
Interestingly, the smart indent works correctly if I have the cursor on an empty line.

I found a workaround by calling `editorPage.smartIndentContents();` twice (in `MBeautify.indentPage()`). It's not the nicest solution though.

**Comment by danielmeer** [comment]
Pull request #112 fixes the issue.

**Comment by davidvarga** [comment]
I forgot to close the issue after merging your PR :)
