### ISSUE TITLE
Expression, that MBeautifier can't handle 

### ISSUE THREAD

**Issue by denissagaydak** [davidvarga/MBeautifier#13]
Hey, David. 

Looks like Beautifier fails on the following code:

[out1, out2] = func([str1, str2], [str3, str4]);

it removes last ");" and code becomes non-compilable. 

Denis

**Comment by davidvarga** [comment]
Hey Denis,
Thanks, I will debug it :)
BR, David

**Comment by davidvarga** [comment]
Hey Denis,
fixed.
BR, David
