### ISSUE TITLE
Problem  when using +/- signs in the first element of matrix assignments

### ISSUE THREAD

**Issue by JohannesTen** [davidvarga/MBeautifier#16]
[-1, 2, 3, 4]   ->   [-, 1, 2, 3, 4] 
[+1, 2, 3, 4]  ->   [+, 1, 2, 3, 4] 

If the +/- sign is on a later position it behaves fine
[1, -2, 3, 4]  -> [1, - 2, 3, 4] 
however, there is an additional withespace create between the +/- sign and the number
I think -2 is easier to read than - 2 in this case

**Comment by davidvarga** [comment]
Fixed in commit 54e8770d2bcf60789dd2b050a683cd86fbf28c6a
