### ISSUE TITLE
Special arithmetic operator cases

### ISSUE THREAD

**Issue by FriesischScott** [davidvarga/MBeautifier#19]
Formatting of arithmetic operators needs to address special cases.

 Two cases I have found were:

* [1 -1] becomes [1 - 1] which has a whole different meaning
* 7E+5 becomes 7E + 5 which is invalid

I have just used it on one file so there might be more cases that have to be considered.

**Comment by davidvarga** [comment]
Thanks for the findings. I have fixed them with the linked commit. There are some other probems with matrixes and cell-arrays, I will fix them in #20.
