### ISSUE TITLE
Inconsistent spacing around minus sign

### ISSUE THREAD

**Issue by homocomputeris** [davidvarga/MBeautifier#26]
Hi,
`[[I,Z];[h*(-K-L),I]] * [[I,Z];[h*(K-L),I]]` 
becomes
`[[I, Z]; [h * (-K - L), I]] * [[I, Z]; [h * (K-L), I]]`
with spaces added only in the first parenthesis.
Commit b931478, MATLAB 2016b.

Somewhat relevant config:

```
<SpecialRule>
<Key>CellArrayIndexing_ArithmeticOperatorPadding</Key>
<Value>0</Value>
</SpecialRule>
<SpecialRule>
<Key>MatrixIndexing_ArithmeticOperatorPadding</Key>
<Value>0</Value>
</SpecialRule>
```

**Comment by davidvarga** [comment]
Hi,
unfortunately I am unable to reproduce this behaviour. (Tried on R2016a 64bit).
Could you add more context (maybe the context has some effect on the formatting).

**Comment by homocomputeris** [comment]
Sorry, I had no idea, that a function call is relevant.
Upper line is before, lower is after:
`result=[[I,Z];[(-K-L)*h,I]]*expm(h*D)*[[I,Z];[(K-L)*h,I]]*result;`
`result = [[I, Z]; [(-K - L) * h, I]] * expm(h*D) * [[I, Z]; [(K-L) * h, I]] * result;`

`result=[[I,Z];[(-K-L)*h,I]]*[[I,Z];[(K-L)*h,I]]*result;`
`result = [[I, Z]; [(-K - L) * h, I]] * [[I, Z]; [(K - L) * h, I]] * result;`
