### ISSUE TITLE
Formatting removes mldivide  \

### ISSUE THREAD

**Issue by homocomputeris** [davidvarga/MBeautifier#27]
`x = A\b;`
becomes
`x = A  b;`

**Comment by davidvarga** [comment]
Thanks for creating this issue. I have committed the fix for the problem.
Please run `MBeautify.setup();` after downloading the fix to make sure that the configuration M file has been updated (the problem was the lack of regexp escaping in the "ValueTo" fields in the configuration file).

**Comment by homocomputeris** [comment]
It's turned out it still removes \ from
`temp = (I + bA * ((eye(2*2*n) - AA)\[I, I]')); `

**Comment by davidvarga** [comment]
Added a commit, seems working now.
