### ISSUE TITLE
Suggestion: power operator should not be separated

### ISSUE THREAD

**Issue by homocomputeris** [davidvarga/MBeautifier#28]
I suggest that power operators ^ and .^ should not be separated by default.
The reason is that in function calls (seems they are affected by matrix indexing settings) it becomes barely readable:
`sqrt(a+b^2)` becomes `sqrt(a+b ^ 2)`
While better variants are:
`sqrt(a+b^2)` or `sqrt(a + b^2)`

**Comment by davidvarga** [comment]
Thanks, good point. Updated the default configuration accordingly.
