### ISSUE TITLE
Convenience function to format multiple files

### ISSUE THREAD

**Issue by girtsf** [davidvarga/MBeautifier#33]
It would be nice if there was a command to format all files matching a given pattern. E.g., MBeautify.formatFiles('**/*.m').

**Comment by davidvarga** [comment]
I will think about this (and as I will have time I will also implement). Maybe a two argument solution, where the first arg is the directory the second one a regular expression would fit better: `MBeautify.formatFiles('D:\mydir', '.*\.m')` or `MBeautify.formatFiles('D:\mydir2', '.+_only_with_postfix\.m')`.

**Comment by girtsf** [comment]
Looks like dir() function accepts globs including ** syntax. So all the .m files under "mydir" could be just "/path/to/mydir/**/*.m". Or "/path/to/mydir2/**/*_only_with_postfix.m" (substitute with windows path naming as appropriate). It wouldn't be as flexible as a regexp, but the code might be just a for loop on results of dir() call to formatFile.

**Comment by davidvarga** [comment]
I checked dir, it supports wildcards even in R2011 so this can be easily implemented. Thanks for the suggestion:)

**Comment by davidvarga** [comment]
I made a commit that extends the interface with a method that can be used like `formatFiles('D:\mydir', 'prefix_*_postfix.m');. Tested on several versions -> I will close the card in some days. Please give me a feedback if you experience anything unexpected.
