### ISSUE TITLE
How to actually "install" these scripts?

### ISSUE THREAD

**Issue by mrdaliri** [davidvarga/MBeautifier#39]
I'm new to Matlab, how can I use them?

Is there any "Scripts" (or "Plugins") section in Matlab where there scripts should placed there?

**Comment by davidvarga** [comment]
Hi,

as everything in Matlab (functions, scripts and classes) must be placed on the Matlab path to make Matlab able to recognize them. Please refer to the "Deployment" section of the Readme of this repository. About the Matlab search path, you can read the documentation: https://de.mathworks.com/help/matlab/matlab_env/what-is-the-matlab-search-path.html
