### ISSUE TITLE
error formatting with  exponential notation

### ISSUE THREAD

**Issue by JianpingCAI** [davidvarga/MBeautifier#40]
For example, "1e-6" is added with a space as "1e -6", which is wrong.

**Comment by davidvarga** [comment]
Could you please give the example with full context? Because e.g. "a=1e-6" is formatted properly. Thanks!

**Comment by JianpingCAI** [comment]
Thanks a lot for your reply.
Sorry that I provided a wrong example, it should be like "1.e-6", this is wrongly formatted to "1.e - 6".
Sorry for the late reply.
Great tool, btw, thanks a lot.

**Comment by davidvarga** [comment]
Thanks for the bug-report. The problem should be gone now.
