### ISSUE TITLE
MatrixIndexing and CellArrayIndexing setting not respected

### ISSUE THREAD

**Issue by galli-a** [davidvarga/MBeautifier#43]
Despite having `MatrixIndexing_ArithmeticOperatorPadding` and `CellArrayIndexing_ArithmeticOperatorPadding` set to 0 in both the m and xml configuration files, code such as

```
b = a(1:end-2);
c = a(end-1);
e = d{1:end-2};
f = d{end-1};
```

is converted to 

```
b = a(1:end - 2);
c = a(end - 1);
e = d{1:end - 2};
f = d{end - 1};
```

The configuration files are the default ones, have not been edited.

Tested on both R2016a and R2017a

**Comment by davidvarga** [comment]
Thanks for the report!
It should work now as expected.
