### ISSUE TITLE
Single indent with multiple lines of comment

### ISSUE THREAD

**Issue by plaitiang** [davidvarga/MBeautifier#46]
MBeautify add a single indent every line of multiple lines comment after run command `MBeautify.formatCurrentEditorPage()`. This isn't happening with single line comment.

Before call command:
```
%This is one line comment
%{
This is
multiline
comment
%}
```
After call `MBeautify.formatCurrentEditorPage()` 10 times.
```
%This is one line comment
%{
          This is
          multiline
          comment
%}
```

**Comment by davidvarga** [comment]
Thanks for the observation. The problem is fixed in the commit.
