### ISSUE TITLE
Suggestion: adding empty line at the end of file and before section

### ISSUE THREAD

**Issue by mike-live** [davidvarga/MBeautifier#49]
I suggest two special rules:

1. Adding one empty line at the end of file
2. Adding one empty line before section start

This code 
```
a = 1 + 1;
%% New Matlab Section
b = 2 + 2;
```
beautified to this code
```
a = 1 + 1;

%% New Matlab Section
b = 2 + 2;

```

**Comment by davidvarga** [comment]
Section comment trailing and preceding new lines and ending new line count now can be configured.

**Comment by mike-live** [comment]
@davidvarga, thanks a million for the quick fixes and the addition of new features!
