### ISSUE TITLE
Anonymous functions in a cell are formatted incorrectly

### ISSUE THREAD

**Issue by stinos** [davidvarga/MBeautifier#54]
```
l = {@(x) strcmp(x, 'True')};
```

gets turned into

```
l = {@(x), strcmp(x, 'True')};
```

notice the incorrect comma added after `@(x)`. This is quite a showstopper :]

**Comment by davidvarga** [comment]
Which version do you use? There was an update on #42, in the latest state I cannot reproduce it (using the default config).

**Comment by stinos** [comment]
Yes sorry you're right, latest version doesn't do this. It does have some other inconsistencies though, I'll create another issue for that
