### ISSUE TITLE
Does this tool provide a way to insert new lines after every semicolon?

### ISSUE THREAD

**Issue by nbro** [davidvarga/MBeautifier#56]
I sometimes see pieces of code of the form

    figure; plot(...)

Honestly, I don't like to have more than one command per line. Does this tool provide a way to insert new lines after every semicolon? If yes, what is the option? If not, do you plan to do it?

**Comment by davidvarga** [comment]
The feauture has been added. You can control it through the "AllowMultipleStatementsPerLine" rule (it defaults to false, therefore the default configuration will already break multiple statements into new lines).
