### ISSUE TITLE
Reference to non-existent field 'SectionPrecedingNewlineCountValue'.

### ISSUE THREAD

**Issue by orwel1984** [davidvarga/MBeautifier#57]
Just downloaded and tried your script. Does'nt seem to work out of the box:

```
>> MBeautify.formatCurrentEditorPage()
Reference to non-existent field 'SectionPrecedingNewlineCountValue'.

Error in MFormatter/performFormatting (line 107)
            nSectionPrecedingNewlines = str2double(obj.SettingConfiguration.SpecialRules.SectionPrecedingNewlineCountValue);

Error in MBeautify.formatCurrentEditorPage (line 218)
            currentEditorPage.Text = formatter.performFormatting(currentEditorPage.Text);
 
```

**Comment by davidvarga** [comment]
I just downloaded and tried - no issue here. Did you add the full directory to the Matlab path?

**Comment by orwel1984** [comment]
I’m on windows 10
And extracted your downloaded files in 
c:/users/documents/Matlab

**Comment by davidvarga** [comment]
Its not enough that the "MBeautifier-master" directory is on the Matlab path, the subdirectories must be also on the path - so please right click on "MBeautifier-master" > Add to the path recursively.

**Comment by orwel1984** [comment]
okay adding subfolders did the trick
