### ISSUE TITLE
Error occurs when ... line break in matrix

### ISSUE THREAD

**Issue by FlorianPfaff** [davidvarga/MBeautifier#59]
Hi,

I just used the tool and liked it. However, it broke my code. Here an MWE
a = [1, 2, 3];
a = [1, a...
    .* 2]

This is reformatted as
a = [1, 2, 3];
a = [1, a, ...
    .* 2]

which is invalid Matlab code.

Thanks for considering to fix it.

FP

**Comment by davidvarga** [comment]
Thanks for the report, I'll take care of it :)

**Comment by davidvarga** [comment]
Fix added: the case when the "..." operator breaks a single element in a container, now the "add commas" option does not add the comma.
