### ISSUE TITLE
It beautify inside some strings!

### ISSUE THREAD

**Issue by simon-r** [davidvarga/MBeautifier#62]
It beautify inside some strings: 

If I use a string like this:
fprintf("------------------- \n");

It will modified to this one (note the space between \ and n):
fprintf(" - - - - - - - - - - - - - - - - - - - \ n");

**Comment by davidvarga** [comment]
Hi,

the syntax str = "abc" was introduced in Matlab R2017a - I was not even aware of it.

For now, the classic str = 'abc' syntax works, I will check how difficult is to support the new notation.

Thanks for the card!

**Comment by davidvarga** [comment]
It has been implemented. Both cahracter array and string array notation are supported from now.
