### ISSUE TITLE
Remove trailing spaces on empty lines

### ISSUE THREAD

**Issue by meerdan** [davidvarga/MBeautifier#63]
Hi,

It would be great to have the option to remove _all_ trailing white space. The MATLAB indentation function (Ctrl+i) already handles this for lines containing code, but it adds spaces on empty lines up to the current indentation level.

The current behavior is like this (I added dots to show the spaces):
```
for true
....
    a = 1;
....
end
```

And I would like this:
```
for true

    a = 1;

end
```

I think something like this regex should do the trick: `regexprep(text, '^\s+$', '', 'lineanchors')`

**Comment by davidvarga** [comment]
Hi,
it seems quite simple to be implemented - I'll take care in short time. 
Thanks for the proposal.

**Comment by davidvarga** [comment]
Hi, I implemented it - in the evening I can push it. i made it default as it can lead to smaller file sizes.
