### ISSUE TITLE
Indent function content

### ISSUE THREAD

**Issue by kupiqu** [davidvarga/MBeautifier#66]
Would you consider adding this option?

**Comment by davidvarga** [comment]
do you mean

```
function myFunction()
     a = 'Should be indented?';
end
```

?

**Comment by kupiqu** [comment]
Yes, as an option

**Comment by kupiqu** [comment]
Would you please consider adding a rule for this?

**Comment by davidvarga** [comment]
I was thinking about this one. Theoretically the idea that I came up with could work, but I have to try it out.  Hopefully next week you'll get an update on the issue.

**Comment by romill93** [comment]
@davidvarga This option is really something we desperately miss. Would be really great to have it. Other than that: Great work :-D

**Comment by iserlohnarchmage** [comment]
Yes, please!

**Comment by meerdan** [comment]
You can configure MATLAB on how to indent your functions. This also affects MBeautifier because it uses the smart indenting feature from MATLAB.

Just go to Preferences -> MATLAB -> Editor/Debugger -> Language
Under "Indenting" there is a a field "Function indenting format" with three options:
- Indent nested functions
- **Indent all functions**
- Classic

The one in bold is the one you want (I prefer this style as well).

Unfortunately, there is no official MATLAB function to set this option. But there is an undocumented one:
```
com.mathworks.services.Prefs.setStringPref('EditorMFunctionIndentType', 'AllFunctionIndent')
```

**Comment by xichen-de** [comment]
> You can configure MATLAB on how to indent your functions. This also affects MBeautifier because it uses the smart indenting feature from MATLAB.
> 
> Just go to Preferences -> MATLAB -> Editor/Debugger -> Language
> Under "Indenting" there is a a field "Function indenting format" with three options:
> 
>     * Indent nested functions
> 
>     * **Indent all functions**
> 
>     * Classic
> 
> 
> The one in bold is the one you want (I prefer this style as well).
> 
> Unfortunately, there is no official MATLAB function to set this option. But there is an undocumented one:
> 
> ```
> com.mathworks.services.Prefs.setStringPref('EditorMFunctionIndentType', 'AllFunctionIndent')
> ```

Thank you very much! Now I finally get it. The [MATLAB-Formatter](https://github.com/affenwiesel/matlab-formatter-vscode) for VS Code indent all functions as well. Since I use VS Code occasionally, it is very nice to unify the style.

**Comment by davidvarga** [comment]
Thank you @meerdan !

Then actually there could be introduced this as option for MBeauty, and controlled through the undocumented MATLAB feature.

**Comment by kupiqu** [comment]
nice!

**Comment by davidvarga** [comment]
Implemented a new special indentation rule based on the proposal of @meerdan: "Indentation_Strategy". MBeautifier provides the exact three options to select from, used in the time of the formatting (then resetting to the one set in MATLAB preferences).

Thanks again all the constructive comments!
Closing the issue.
