### ISSUE TITLE
Indentation width option

### ISSUE THREAD

**Issue by kupiqu** [davidvarga/MBeautifier#67]
wondering, is there an option to change default indent of 4 whitespace characters? I personally like 2 better?

**Comment by davidvarga** [comment]
MBeautifier is currently using smart indent of MATLAB - Will check if I can affect it.

**Comment by kupiqu** [comment]
Thanks for considering

**Comment by davidvarga** [comment]
Hi, it is practically done (indentation character: white space or tabulator + indendation level). I cannot push it at the moment, but in the evening it will be online.

**Comment by kupiqu** [comment]
thank you
