### ISSUE TITLE
Configuration rules do not get updated

### ISSUE THREAD

**Issue by cszczepaniak** [davidvarga/MBeautifier#72]
A change in the XML configuration does not change the formatting behavior. I tried running `MBeautify.formatCurrentEditorPage` on the following dummy file:

```
if(true)
end
```
With the default setting of 1 for the right padding on the `if` keyword, the formatted output looked correct:
```
if (true)
end
```
If I change the configuration rule to the following:
```
...
<KeyworPaddingRule>
    <Keyword>if</Keyword>
    <RightPadding>4</RightPadding>
</KeyworPaddingRule>
...
```
I expect there to be four spaces between `if` and `(true)`, but the formatted output looks the same as before.

**Comment by davidvarga** [comment]
Was fixed directly by fixing your other [issue ](https://github.com/davidvarga/MBeautifier/issues/71).
