### ISSUE TITLE
Can't manage to get the shortcuts to work

### ISSUE THREAD

**Issue by RedeyeFR** [davidvarga/MBeautifier#85]
Hi, as i'm using MBeautify.createShortcut('editorpage') in my script i don't have a new shortcut created in my preference > keyboard > shortcut.

Could someone explain me what did i miss ? Or maybe it doesn't work ?

**Comment by davidvarga** [comment]
Hi,

it is not creating a new keyboard shortcut, but crates a button on the ribbon of MATLAB. In older version under the tab "SHORTCUTS", newer MATLAB version - starting with 2018a: Home -> Favorites.
