### ISSUE TITLE
Problem with unary plus and unary minus

### ISSUE THREAD

**Issue by davidvarga** [davidvarga/MBeautifier#9]
http://www.mathworks.com/help/matlab/ref/uplus.html

**Comment by MaxGaukler** [comment]
Is there any point in the code at which I could start fixing this, or is it nearly impossible to do so with the current structure?

**Comment by davidvarga** [comment]
Every operator replacement is done in `performFormatting/performReplacementsSingleLine`. MBeautifier is not an interpreter (the original use case was too simple to implement one and also I was expecting that Mathworks will include an interpreter based formatter into the editor - which did not happen unfortunately) therefore this is a really difficult task using this "brute-force" approach. The trick would be to make a difference between the binary and the unary case based on the context (where the context means one continous line).

**Comment by davidvarga** [comment]
I have commited a version to handle unary plus and unary minus. It is far not the final version, but can handle most of the cases. Feel free to give a feedback or contribute :)
