### ISSUE TITLE
Broken formatting

### ISSUE THREAD

**Issue by VorpalBlade** [davidvarga/MBeautifier#90]
```
Mr = @(lambda) ([cos(lambda), sin(lambda); -sin(lambda), cos(lambda)]);
```
now turns into
```
Mr = @(lambda) ([cos, (lambda), sin, (lambda); -sin, (lambda), cos, (lambda)]);
```

The recent fix for list concatenations likely broke this.

**Comment by davidvarga** [comment]
Hi,

yeah you are right - actually my fix of the bug introduced by [this commit](https://github.com/davidvarga/MBeautifier/commit/7891a03ddc21ca6fba156f94474a4342b3fff91e) causing this.

I try to revert "my fix" and patch up the originnal commit.

**Comment by davidvarga** [comment]
It should be fixed for now.
